// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "ffmall/app/frontend/biz/router/auth"
	home "ffmall/app/frontend/biz/router/home"
	product "ffmall/app/frontend/biz/router/product"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	product.Register(r)

	auth.Register(r)

	home.Register(r)
}
